"""create initial tables

Revision ID: 092b1636c271
Revises: 
Create Date: 2026-04-05 10:22:12.490671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092b1636c271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_id', sa.String(length=20), nullable=True, comment='原始 HTML 資料中的 ID（如 p1, p2）'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True, comment='世代（第幾世）'),
    sa.Column('branch', sa.String(length=50), nullable=True, comment='支系'),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.String(length=50), nullable=True),
    sa.Column('death_year', sa.String(length=50), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('spouse', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True, comment='簡介'),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_index(op.f('ix_persons_old_id'), 'persons', ['old_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('add_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending / approved / rejected'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.String(length=50), nullable=True),
    sa.Column('spouse', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('father_person_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True, comment='申請說明'),
    sa.Column('reject_reason', sa.Text(), nullable=True, comment='拒絕原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['father_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_requests_id'), 'add_requests', ['id'], unique=False)
    op.create_index(op.f('ix_add_requests_status'), 'add_requests', ['status'], unique=False)
    op.create_table('edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False, comment='修改內容，格式：{欄位: {old: 原值, new: 新值}}'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_requests_id'), 'edit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_edit_requests_status'), 'edit_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_requests_status'), table_name='edit_requests')
    op.drop_index(op.f('ix_edit_requests_id'), table_name='edit_requests')
    op.drop_table('edit_requests')
    op.drop_index(op.f('ix_add_requests_status'), table_name='add_requests')
    op.drop_index(op.f('ix_add_requests_id'), table_name='add_requests')
    op.drop_table('add_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_persons_old_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
